spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5s
  security:
    oauth2:
      client:
        registration:
          booking-service:
            provider: keycloak
            client-id: booking-service
            client-secret: 0ZsfkyWvYAkmpKltAz8LDTlDJtDF7CAj
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8180/realms/travel
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8180/realms/travel
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/booking_service
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
management:
  server:
    port: 9002
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway,mappings
  endpoint:
    health:
      show-details: always
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
  instance:
    prefer-ip-address: true
flight-service:
  base-url: http://host.docker.internal:8081
app:
  notifications:
    exchange: notifications.exchange
    routingKey:
      reservationCreated: reservation.created
      reservationCancelled: reservation.cancelled
      reservationUpdated: reservation.updated
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org:
      springframework:
      amqp: DEBUG